cmake_minimum_required(VERSION 3.28)
project(gmurman_5)

set(CMAKE_CXX_STANDARD 17)

add_executable(gmurman_5 main.cpp
        92_task/92_task.hpp
        92_task/92_task.hpp
        93_task/93_task.hpp
        95_task/95_task.hpp
        98_task/98_task.hpp
        100_task/100_task.hpp
        102_task/102_task.hpp
        104_task/104_task.hpp
        107_task/107_task.hpp)
