cmake_minimum_required(VERSION 3.28)
project(NTA_2)

set(CMAKE_CXX_STANDARD 17)

add_executable(NTA_2 main.cpp
        inc/convert.hpp
        src/convert.cpp
        task8_1/task8_1.cpp
        task8_1/task8_1.hpp
        task8_24/task8_24.hpp
        task8_24/task8_24.hpp
        task8_24/task8_24.cpp
        task30_3/task30_3.hpp
        task30_3/task30_3.cpp
        task_41/task_41.hpp
        task_41/task_41.cpp)
